name: Xcode CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4

      - name: Show Xcode version
        run: xcodebuild -version

      - name: List schemes
        run: xcodebuild -list -project MapleOCR.xcodeproj

      - name: Build
        run: |
          xcodebuild \
            -project MapleOCR.xcodeproj \
            -scheme MapleOCR \
            -destination 'platform=macOS' \
            build
